name: prizo-app
region: nyc

services:
  - name: prizo-api
    source_dir: apps/api
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    routes:
      - path: /api
    envs:
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD
        type: SECRET
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_AND_BUILD
        type: SECRET
      - key: CLOUDINARY_CLOUD_NAME
        scope: RUN_AND_BUILD
        type: SECRET
      - key: CLOUDINARY_API_KEY
        scope: RUN_AND_BUILD
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        scope: RUN_AND_BUILD
        type: SECRET
      - key: CLOUDINARY_UPLOAD_PRESET
        scope: RUN_AND_BUILD
        type: SECRET

static_sites:
  - name: prizo-web
    source_dir: apps/web
    build_command: |
      npm ci
      npm run build
      npm run export
    output_dir: out
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD
        type: SECRET
      # Si no defines NEXT_PUBLIC_RATE_URL, el frontend usará "/api/rate"
      - key: NEXT_PUBLIC_RATE_URL
        scope: RUN_AND_BUILD
        type: SECRET
      # Si prefieres forzar Node 18 LTS
      - key: NODE_VERSION
        value: 18.20.4
        scope: RUN_AND_BUILD